THUB-15: initial commit
SU-SWS/taiwan_hub_subtheme pull request #13
Opened 2024-06-29 01:51 UTC by jenbreese

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2024-07-03 22:15 UTC, rebeccahongsf requested changes
Everything is looking good 👀 Just the responsive banner bug and a few questions!

2024-07-03 22:15 UTC, rebeccahongsf commented on src/scss/components/banner/_overlay-banner.scss
> +            max-width: calc(50% - 70px);
The inline banner content appears to span outside of the viewport for 767px and smaller screens 👀 

![image](https://github.com/SU-SWS/taiwan_hub_subtheme/assets/34019925/13d8056a-9212-46c1-9d19-42d3851f469b)

2024-07-03 22:15 UTC, rebeccahongsf commented on src/scss/components/banner/_overlay-banner.scss
> +    background: $su-color-black url("../assets/png/banner-bg.jpg") no-repeat 100% / cover;
Is the red geometric background attached to the `.thub-wrapper--banner-overlay` class to account for the scenario when the user doesn't add a card? 😃 

I was wondering since I initially thought it would make more sense to have it attached to the background of the `.su-card__contents` class.

2024-07-08 22:26 UTC, jenbreese commented on src/scss/components/banner/_overlay-banner.scss
> +            max-width: calc(50% - 70px);
@rebeccahongsf This issues appears to be fixed. Can you retry it?

2024-07-08 22:26 UTC, jenbreese commented on src/scss/components/banner/_overlay-banner.scss
> +    background: $su-color-black url("../assets/png/banner-bg.jpg") no-repeat 100% / cover;
Yes, I have it there for the user not adding an image with the banner.

2024-07-09 00:05 UTC, jenbreese commented
@rebeccahongsf When you have time, I think I have it all fixed. I adjusted the divider on the footer too for mobile screens.

2024-07-09 02:30 UTC, rebeccahongsf commented on src/scss/components/banner/_overlay-banner.scss
> +    background: $su-color-black url("../assets/png/banner-bg.jpg") no-repeat 100% / cover;
There is a black background attached to `.su-hero__media` for when there is no image:
<img width="1054" alt="image" src="https://github.com/SU-SWS/taiwan_hub_subtheme/assets/34019925/8917bc91-7fcc-4c84-90be-2167c356ac89">


Screen width: 1512px
![image](https://github.com/SU-SWS/taiwan_hub_subtheme/assets/34019925/acdef3ec-5aae-4db2-9741-8313592bded2)

Screen width: 650px
![image](https://github.com/SU-SWS/taiwan_hub_subtheme/assets/34019925/9ed97d44-c78d-472c-bd24-c30dd999fd57)

2024-07-09 02:32 UTC, rebeccahongsf requested changes
The banner with image looks amazing 😄 Just a small issue with the no-image scenario then we should be good to go!

2024-07-09 17:49 UTC, jenbreese commented
@rebeccahongsf this is ready for you. I fixed the no image version.

2024-07-09 19:10 UTC, rebeccahongsf commented on src/scss/components/banner/_overlay-banner.scss
> +    background: $su-color-black url("../assets/png/banner-bg.jpg") no-repeat 100% / cover;
Huzzah! The no-image scenario has been resolved :) Thank you @jenbreese 

![image](https://github.com/SU-SWS/taiwan_hub_subtheme/assets/34019925/6759dc32-b9a1-4214-95c9-4c798cf95394)

2024-07-09 19:14 UTC, rebeccahongsf approved these changes
LGTM 🎉 Thank you again, @jenbreese

2024-07-09 19:28 UTC, merged